[package]
name = "triangle_geometry"
version = "0.1.0"
authors = ["Will Usher <willusher.life@gmail.com>"]
edition = "2021"

[dependencies]
embree = { path = "../../" }
support = { path = "../support" }
ultraviolet = "0.9"

